pipeline:
  build:
    image: docker
    environment:
    commands:
      - docker build -t eu.gcr.io/jeffrey-197808/api:${DRONE_COMMIT_SHA:0:8} .
      - docker login -u _json_key -p "$(cat $GOOGLE_APPLICATION_CREDENTIALS)" https://gcr.io
      # - docker push eu.gcr.io/jeffrey-197808/api:${DRONE_COMMIT_SHA:0:8}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
