pipeline:
  build:
    image: docker
    environment:
    commands:
      - docker build -t eu.gcr.io/jeffrey-197808/api:${DRONE_COMMIT_SHA:0:8} .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
