pipeline:
  build:
    image: docker
    commands:
      - docker build -t eu.gcr.io/jeffrey-197808/api:${DRONE_COMMIT_SHA} .
      - docker push eu.gcr.io/jeffrey-197808/api:${DRONE_COMMIT_SHA}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
