version: '2'
services:
  api:
    build: ./api
    depends_on:
      - postgres
    volumes:
      - ./config:/config
    environment:
      CONFIG: /config/config-prod.yml
  postgres:
    image: postgres:10.1
    volumes:
      - ./pgdata:/var/lib/postgresql/data
