export default {
  continue                      : { code: 100, label: 'Continue' },
  switchingProtocols            : { code: 101, label: 'Switching Protocols' },
  ok                            : { code: 200, label: 'OK' },
  created                       : { code: 201, label: 'Created' },
  accepted                      : { code: 202, label: 'Accepted' },
  nonAuthoritativeInformation   : { code: 203, label: 'Non-Authoritative Information' },
  noContent                     : { code: 204, label: 'No Content' },
  resetContent                  : { code: 205, label: 'Reset Content' },
  partialContent                : { code: 206, label: 'Partial Content' },
  multipleChoices               : { code: 300, label: 'Multiple Choices' },
  movedPermanently              : { code: 301, label: 'Moved Permanently' },
  found                         : { code: 302, label: 'Found' },
  seeOther                      : { code: 303, label: 'See Other' },
  notModified                   : { code: 304, label: 'Not Modified' },
  useProxy                      : { code: 305, label: 'Use Proxy' },
  temporaryRedirect             : { code: 307, label: 'Temporary Redirect' },
  badRequest                    : { code: 400, label: 'Bad Request' },
  unauthorized                  : { code: 401, label: 'Unauthorized' },
  paymentRequired               : { code: 402, label: 'Payment Required' },
  forbidden                     : { code: 403, label: 'Forbidden' },
  notFound                      : { code: 404, label: 'Not Found' },
  methodNotAllowed              : { code: 405, label: 'Method Not Allowed' },
  notAcceptable                 : { code: 406, label: 'Not Acceptable' },
  proxyAuthenticationRequired   : { code: 407, label: 'Proxy Authentication Required' },
  requestTimeout                : { code: 408, label: 'Request Timeout' },
  conflict                      : { code: 409, label: 'Conflict' },
  gone                          : { code: 410, label: 'Gone' },
  lengthRequired                : { code: 411, label: 'Length Required' },
  preconditionFailed            : { code: 412, label: 'Precondition Failed' },
  payloadTooLarge               : { code: 413, label: 'Payload Too Large' },
  uriTooLong                    : { code: 414, label: 'URI Too Long' },
  unsupportedMediaType          : { code: 415, label: 'Unsupported Media Type' },
  rangeNotSatisfiable           : { code: 416, label: 'Range Not Satisfiable' },
  expectationFailed             : { code: 417, label: 'Expectation Failed' },
  upgradeRequired               : { code: 426, label: 'Upgrade Required' },
  internalServerError           : { code: 500, label: 'Internal Server Error' },
  notImplemented                : { code: 501, label: 'Not Implemented' },
  badGateway                    : { code: 502, label: 'Bad Gateway' },
  serviceUnavailable            : { code: 503, label: 'Service Unavailable' },
  gatewayTimeout                : { code: 504, label: 'Gateway Timeout' },
  httpVersionNotSupported       : { code: 505, label: 'HTTP Version Not Supported' }
};
