# the schema allows the following query:
type Query {
  currentUser: User
  onboardingProgress: [String]
  locality(
    lat: String!
    lng: String!
  ): Locality
  providers(
    offset: Int!
    limit: Int!
  ): [User]
  services: [Service]
  serviceCategories: [Service]
  conversation(
    conversationId: String!
  ): Conversation
}
type Locality {
  name: String!
  country: Country!
}
type Subscription {
  newMessage(conversationId: String!): Message
}
type Mutation {
  newMessage(conversationId: String!, message: String!): Message
  updatePassword(password: String!): Boolean
}
