type Service {
  id: String!
  name: String!
}
type Provider {
  id: String!
  name: String!
}
type User {
  id: String!
  firstName: String!
  lastName: String!
  email: String
  phone: String
  profilePicture: String
  phoneNumber: String
}
type Message {
  id: String!
  message: String!
  type: MessageType!
  time: String!
}
# the schema allows the following query:
type Query {
  currentUser: User
  locality(
    lat: String!
    lng: String!
  ): Locality
  providers: [Provider]
  services: [Service]
  conversation(
    conversationId: String!
  ): [Message]
}
type Country {
  id: String!
  name: String!
  code: String!
}
type Locality {
  name: String!
  country: Country!
}
enum MessageType {
  incoming
  outgoing
}
type Subscription {
  newMessage(conversationId: String!): Message
}
